version: '3.9'
volumes:
  pgadmin:
  dbbackups:
  postgis-data:

services:
  db:
    image: kartoza/postgis:15-3.3
    volumes:
      - ./postgis-data/:/var/lib/postgresql
      - /opt/backup/dbbackups/:/backups
    environment:
      - POSTGRES_DB=gis,gwc
      - POSTGRES_USER=admin
      - POSTGRES_PASS=root
      - ALLOW_IP_RANGE=192.168.100.0/24
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: "exit 0"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.buro
      PGADMIN_DEFAULT_PASSWORD: qweqwe
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
  dbbackups:
    image: kartoza/pg-backup:latest
    hostname: pg-backups
    volumes:
      - /opt/backup/dbbackups/:/backups
    environment:
      - DUMPPREFIX=PG_db
      - POSTGRES_USER=admin
      - POSTGRES_PASS=qweqwe
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    restart: always
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
